services:
  postgres:
    image: postgres:16-alpine
    container_name: freshbox-postgres
    environment:
      POSTGRES_USER: freshbox
      POSTGRES_PASSWORD: freshbox
      POSTGRES_DB: freshbox
    ports:
      - "5433:5432"
    volumes:
      - freshbox_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: freshbox-redis
    ports:
      - "6380:6379"

  minio:
    image: minio/minio:latest
    container_name: freshbox-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: freshbox-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 4;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/pomar-fresh --ignore-existing;
      mc anonymous set public local/pomar-fresh;
      exit 0;
      "

volumes:
  freshbox_pg:
  minio_data:
